const student = [{
    "id": 1,
    "first_name": "Jozef",
    "last_name": "Cockney",
    "email": "jcockney0@washington.edu"
  }, {
    "id": 2,
    "first_name": "Eyde",
    "last_name": "Winslet",
    "email": "ewinslet1@sina.com.cn"
  }, {
    "id": 3,
    "first_name": "Bennie",
    "last_name": "Bielfeldt",
    "email": "bbielfeldt2@angelfire.com"
  }, {
    "id": 4,
    "first_name": "Melli",
    "last_name": "Wolfenden",
    "email": "mwolfenden3@desdev.cn"
  }, {
    "id": 5,
    "first_name": "Von",
    "last_name": "Chrippes",
    "email": "vchrippes4@t.co"
  }, {
    "id": 6,
    "first_name": "Artemis",
    "last_name": "Paulucci",
    "email": "apaulucci5@wiley.com"
  }, {
    "id": 7,
    "first_name": "Tait",
    "last_name": "Ilson",
    "email": "tilson6@google.com"
  }, {
    "id": 8,
    "first_name": "Madelyn",
    "last_name": "McPike",
    "email": "mmcpike7@europa.eu"
  }, {
    "id": 9,
    "first_name": "Augustus",
    "last_name": "Martynikhin",
    "email": "amartynikhin8@amazon.com"
  }, {
    "id": 10,
    "first_name": "Alanson",
    "last_name": "Rudwell",
    "email": "arudwell9@hhs.gov"
  }, {
    "id": 11,
    "first_name": "Ayn",
    "last_name": "Grigoriev",
    "email": "agrigorieva@constantcontact.com"
  }, {
    "id": 12,
    "first_name": "Neda",
    "last_name": "Mityushkin",
    "email": "nmityushkinb@histats.com"
  }, {
    "id": 13,
    "first_name": "Geneva",
    "last_name": "Calterone",
    "email": "gcalteronec@qq.com"
  }, {
    "id": 14,
    "first_name": "Cullie",
    "last_name": "Duny",
    "email": "cdunyd@pinterest.com"
  }, {
    "id": 15,
    "first_name": "Myrtia",
    "last_name": "Eady",
    "email": "meadye@topsy.com"
  }]

  module.exports = student